### PR TITLE
SQL speedies

### PR DESCRIPTION
**Pull request by the-dunnock**
Added index to table so when requesting the hit count. Query resolves loads faster.

Added index to upgrade action.

### CODE REVIEW

**Comment by jpdevries** [comment]
this is awesome! anything need to happen to seamlessly handle upgrades?

**Comment by the-dunnock** [comment]
Just create new package and upgrade should go cleanly, if the database is humongous the alter table to add index can take a moment.

**Comment by jpdevries** [comment]
so cool. thanks!

**Comment by jpdevries** [comment]
updated to 1.2.1 on the extras repo

**Pull request merged**
